### ISSUE TITLE
UX feedback for when poiId does not exist

### ISSUE THREAD

**Issue by rvorias** [BibliothecaForAdventurers/realms-react#121]
For unexisting poiIds it would be nice if the user gets either feedback on the asset screen, or the render renders it as "NoId" or something 

![image](https://user-images.githubusercontent.com/21060408/167222476-712da5cf-a2ec-474a-8483-bc1c51e840a9.png)

**Comment by rvorias** [comment]
I was thinking of adding "max" key to the pois definitions, but I think it's better if we poll the source data for it.

**Comment by rvorias** [comment]
I think abrax has some ideas regarding this at the contract level.

**Comment by ponderingdemocritus** [comment]
@lordabrax assigning, or close if this is complete
