### ISSUE TITLE
OpenQuill Committee Management and Realms Submissions Incentives

### ISSUE THREAD

**Issue by Pinky420** [BibliothecaForAdventurers/realms-react#122]
One thing that would help me explain the process is if the OpenQuill judging process etc was more clearly outlined, also the possibility of a Realms additional incentive (a First Scribe NFT or $LORDS or something) would help community managers more effectively sell it to writers and artists.

**Comment by ponderingdemocritus** [comment]
We do plan to provide incentives to OpenQuill, but the plan is to do this after the launch of Bibliopedia

**Comment by Pinky420** [comment]
Bibliopedia being a Wikipedia clone I am guessing? That works well for me, just wondering if can advertise that as on the roadmap to other writers? Currently as I gather from Loot OpenQuill and Divine chatter, 3 people from the communities of each project listed are submitted to the committee as judges of content. That is at least what i am seeing as the proposed model that Loothero, Banners and Timshel have spoken on. Where those 3 people come from and whom they are is something that could be done via competition for 1 or 2 of the spots, to try and find an active community member who reads a lot and is a decent editor. With a core or noble lord in the other spot to avoid permissionless paralysis. I think the 3 member model works quite well as it always has to have a majority vote from each project to carry. Open to any feedback.

**Comment by Pinky420** [comment]
I would be hesitant to sleep on this issue, currently the level of submissions compared to level expected is orders of magnitude less. I cannot speak to this part, as I am not on that side of the team. To me, the current Rewards submission of:

**Comment by Pinky420** [comment]
ROUND 1 REWARD POOL: 

5 ETH + various Lootverse NFTs

An opportunity for inclusion in the Genesis Scrolls short story Compendium
Learning!
Community!
Glory!
Plus ETH and other token rewards

Does not incentivize web 2 or analog authors to work on the project. 
5e = 10k = 2 months work from their Patreon subscribers pay. 

Lootverse NFTs only have implied value to people knowledgeable about the ENTIRE lootverse, the Learning, Community and Glory IMO has not been a sufficient incentive to get to the threshold needed for more than bare-bones Lore.

**Comment by RedBeardEth** [comment]
Closing until further in development pipeline
