### ISSUE TITLE
Rewards Claiming

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#127]

**Comment by micksabox** [comment]
Desiege is launching on the StarkNet Goerli Testnet. In order to integrate into games on StarkNet mainnet, a bridge middleware needs to be developed. This functionality will check the balance of rewards for an account on testnet, verify the user has earned Desiege reward contributions, and finally issue rewards on the target network. 

See the [`useUserReward`](https://github.com/BibliothecaForAdventurers/realms-react/blob/main/apps/atlas/src/hooks/desiege/useUserReward.tsx) hook in the realms-react repo for understanding how to fetch and determine game reward contributions for a given account address.

**Comment by micksabox** [comment]
Preventing double-claiming of rewards for a given game requires stateful storage of reward claims. The storage should contain a mapping of `accountAddress`,`gameId` and a boolean flag indicating the claim was processed. If a claim was already made for an account and gameId, subsequent reward claims should fail.

**Comment by ponderingdemocritus** [comment]
This sounds like a nice solution. Let's just map rewards to a storage struct per game and per address, then the user can simply claim each game at a time.
