### ISSUE TITLE
V2: Add markdown toolbar and guidance

### ISSUE THREAD

**Issue by rvorias** [BibliothecaForAdventurers/realms-react#128]

**Comment by rvorias** [comment]
Do we want to have an interactive toolbar?
Rn i implemented it as 
![image](https://user-images.githubusercontent.com/21060408/167586836-379d1bed-3c8f-445d-9f4b-3286d1c3601c.png)

**Comment by ponderingdemocritus** [comment]
let's ship this as-is for testing, then iterate
