### ISSUE TITLE
AMM UI Polish

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#155]
Too add
- [x] Clicking 'trade' in the table should add that resource to the trade panel
- [x] If a resource is in the panel then the 'trade' button should be in a disabled state
- [x] Figure below total 'Lords' on a trade is the users balance (currently is slippage)
- [x] Add users balance of that resource below the select dropdown [have added placeholder]
- [x] restrict user from trying to buy more than their lords balance
- [x] restrict user from selling more than their resource balance

Bugs:
- [x] Dragonhide price not displaying

**Comment by ponderingdemocritus** [comment]
Need to get this over the line - @tenoxious could you please complete or reassign

**Comment by tenoxious** [comment]
@ponderingdemocritus please verify. last 3 items should be in.
