### ISSUE TITLE
Add connect to networks in dropdown

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#156]
The current connection is baked into the account page. This should be in a dropdown when the user clicks the network button

**Comment by ponderingdemocritus** [comment]
@RedBeardEth are you going to hit this? Otherwise @micksabox you should pick this up

**Comment by RedBeardEth** [comment]
It probably makes sense to have a standard interface across assets (Desiege, Atlas etc)

**Comment by RedBeardEth** [comment]
I think @ponderingdemocritus is currently doing the actual account panel modal - this is more in reference to the buttons opening that panel 
![image](https://user-images.githubusercontent.com/90423049/171322394-1f31175d-e47f-4278-8136-271dddba48d8.png)

Its probably a better UX to have those initial connect buttons inside a dropdown rather than having to open the panel and then connect

**Comment by micksabox** [comment]
Assuming drop down has two items:

- Connect Eth
- Connect StarkNet

Any thoughts on: 
Should show and select testnets?

How does this work on mobile?

Should trigger Button open dropdown and **also** trigger route navigation to Account panel?

**Comment by ponderingdemocritus** [comment]
Valid point. Yes, the goal is to unclutter the UI of information that is rarely needed.

Perhaps the best solution is one button with the L2 address, in the drop-down, there is the L1 address.

**Comment by micksabox** [comment]
Ok that works great. Will also work the same for the Lords button, that should be persistent always but it can show the L2 balance primarily, and be augmented with L1 balance after connect.

**Comment by micksabox** [comment]
![Screen Shot 2022-06-03 at 12.22.26 AM.png](https://images.zenhubusercontent.com/6279ba2916dee86ce5beecd5/60cd147a-9c9b-48aa-a6e4-4eee2c8f4c5c)

**Comment by micksabox** [comment]
![Screen Shot 2022-06-03 at 12.28.46 AM.png](https://images.zenhubusercontent.com/6279ba2916dee86ce5beecd5/86414b30-482f-44df-b0ee-2ae03e96f91c)

**Comment by micksabox** [comment]
That's latest mockup of the networks dropdown, it's a component so can be tweaked, simplifies as discussed. Also includes changes to the Lords balance indicator, and I've removed volume with plans to place elsewhere.

**Comment by ponderingdemocritus** [comment]
I like it! Let's ship it
