### ISSUE TITLE
Storybook across monorepo

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#159]

**Comment by micksabox** [comment]
Ran into some build errors configuring this at monorepo root, wasn't able to import tailwind and got this error when running `yarn start`. 
```
Error: Could not find a production build in the 'realms/realms-react/apps/atlas/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
```

The other option would be to configure these at the individual package level.

**Comment by micksabox** [comment]
The goal was to get all stories across monorepo displaying in a single instance
![Screen_Shot_2022-06-02_at_9.19.05_AM.png](https://images.zenhubusercontent.com/6279ba2916dee86ce5beecd5/6b7cd3b0-6975-4645-837e-0342ffbb6d6f)

**Comment by ponderingdemocritus** [comment]
nice! The goal is that we can host this somewhere with polished components.

**Comment by micksabox** [comment]
Made progress on this over the weekend. Configured tailwind (had to lift config from atlas to the root) and also fixed the build error (needed to delete `cache.config.js` for some reason and re-add).

Just need to add support for Emotion 11 and will submit a PR.
