### ISSUE TITLE
Error message for indexer 400

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#160]
<img width="2164" alt="Screen Shot 2022-05-31 at 10 21 24 PM" src="https://user-images.githubusercontent.com/2997810/171315096-982f562f-7eba-4739-a6be-3a9ed9bcbd0e.png">

**Comment by RedBeardEth** [comment]
It looks like youre querying the mainnet indexer, which is quite out of sync with Goerli and settling branch frontend

Add `NEXT_PUBLIC_NETWORK=goerli` to .env

**Comment by micksabox** [comment]
Closing as resolved
