### ISSUE TITLE
Add filter for Realm State

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#161]
Add filter for the Realms state - so people can only see the L2 settled realms (as that is what is attackable)

**Comment by micksabox** [comment]
This is another filter for the Realms list, so plan is to add to the filter toolbar @ponderingdemocritus ![Screen Shot 2022-06-02 at 10.06.42 PM.png](https://images.zenhubusercontent.com/6279ba2916dee86ce5beecd5/6cdebf2a-595f-4c18-b0a7-1ec86a90521d)

I feel the toolbar buttons could benefit from having checkbox / dropdown indicators, which would be part of the theme.

**Comment by micksabox** [comment]
`Attackable` doesn't sound right, maybe just `Settled`

**Comment by ponderingdemocritus** [comment]
yes, exactly this is the plan. 'Settled' makes sense
