### ISSUE TITLE
Add asset count in filter views

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#163]
The same logic can be applied to all:

- [x] Realms view
- [ ] Crypts view
- [ ] GA view
- [ ] Loot view

@tenoxious do we get a total number back in the query? or only a paginated list?

**Comment by tenoxious** [comment]
i'll add this

**Comment by ponderingdemocritus** [comment]
did this get completed?

**Comment by tenoxious** [comment]
@ponderingdemocritus realms asset count is in
others will need to port to new indexer first

**Comment by ponderingdemocritus** [comment]
ok nice, let's close this
