### ISSUE TITLE
Bundle analyzer and bundle size trimming

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#164]

**Comment by micksabox** [comment]
Optimize bundle size by refactoring:

- `react-moment` to `date-fns`
- other optimization opportunities found in treemap

**Comment by micksabox** [comment]
https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by micksabox** [comment]
I ran webpack-bundle-analyzer but couldn't find moment (maybe its on a branch).
![Screen Shot 2022-06-07 at 11.45.59 PM.png](https://images.zenhubusercontent.com/6279ba2916dee86ce5beecd5/b8f4f47f-a6d3-4946-9d7e-9d2b515128ab)

This tree view doesn't segment based on Next page so it's hard to optimize at a per page level (ex. Desiege vs Atlas which have different imports).  Looking for a better tool is next step.

**Comment by ponderingdemocritus** [comment]
How did we go with this?

**Comment by micksabox** [comment]
Haven't found the right tool to be able to optimize the bundle.

**Comment by ponderingdemocritus** [comment]
@tenoxious do you have a preferred bundle anyalzer?

**Comment by tenoxious** [comment]
> @tenoxious do you have a preferred bundle anyalzer?

i do not
