### ISSUE TITLE
Custom saved asset lists

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#166]
Currently, we have a `favorite realms` tab in the filter view. @LordSquiddy had the great idea of giving users the ability to create custom lists for purposes.

Eg:
- Fav raiding list
- Fav personal list
- Fav buy list 
etc

I am thinking we do it all in local storage? @tenoxious

**Comment by micksabox** [comment]
Working on this in #198 

TODO
- [ ] Handle empty lists / reaching end of list
- [ ] Handle wallet not connected
- [ ] Manage cursor when navigating from other areas of app (default initialization of component state)
