### ISSUE TITLE
Slight lag between page transitions

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#168]
The refactor into segments has delivered a huge performance boost. Now each page is async loading on page transition.

This has brought a slight lag from clicking navigation to the page loading. I am thinking we need a full-page loader to improve the UX. This might be being pedantic. 

What are everyone's thoughts on this?

**Comment by RedBeardEth** [comment]
This seems much less noticeable to me now - so doesn't seem necessary @ponderingdemocritus 

The next major version of Next (RFC at https://nextjs.org/blog/layouts-rfc) should optimise the separated layouts/routes further (more similar to Nuxt approach) which should make it less noticeable

**Comment by ponderingdemocritus** [comment]
yeah ok - let's close this
