### ISSUE TITLE
Add query string searches for asset pages

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#171]
**Problem**
Sometimes within the app, you want to directly go to a filtered view of your realms. 

'Your Realms' in the `/realm` view.

Currently if you nav to this page you start on the 'all realms' page

Thinking we make a query string pattern where you can push to specific views

**Comment by RedBeardEth** [comment]
So like `/realm?view=yourRealms`

**Comment by ponderingdemocritus** [comment]
yes exactly -> then we can push users to that page easily

**Comment by tenoxious** [comment]
this should be done already, right?
https://alpha-settling.bibliothecadao.xyz/realm/1

**Comment by ponderingdemocritus** [comment]
This was in reference to the actual list page, the query string would take you to a specific tab

**Comment by ponderingdemocritus** [comment]
@r0man1337 can you confirm you can take this?

**Comment by tenoxious** [comment]
this should be fixed
