### ISSUE TITLE
Client Side Validation

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#183]
There are a number of interactions we may wish to validate on client-side before sending to Starknet/Ethereum, and will likely become more important/complex as the multicall is developed.

- [ ] Adequate resource balance before adding buildings, troops
- [ ] Have grid space available for constructing building
- [ ] Food resource management (both troops and storehouse construction)
- [x] Have attacking army before initiating raid
- [x] Defending Realm is not the same Orders

....

**Comment by micksabox** [comment]
Good to point out that we need to keep in mind what transactions are queued in the `TransactionQueueContext`. For example, if a `claim_resources` (harvest) tx is added to the transaction queue, the wallet will have an adequate balance for transactions after that.

**Comment by micksabox** [comment]
- Attacking army cooldown is expired before raiding
