### ISSUE TITLE
Realms Landing Page

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#185]
We need a responsive (mobile first) landing page with various sections. All sections will be of the same height with the exception of one: The FAQ section. Most sections will have a large background image, which we will need multiple sizes for to responds to aspect ratio changes from one device to another.
The exported, work in progress mockups and illustrations can be found in this google drive folder:
https://drive.google.com/drive/folders/12Pq2lSFQJnLJ76GGW0GY3gynP-PfSoto

Here is the desktop version of what we currently have:
![desktop.png](https://images.zenhubusercontent.com/62c16d2d8b90105ae2f49f24/eb61ce8b-46ff-4af3-a5e7-f14a1d6c8ecb
)

**Comment by RedBeardEth** [comment]
Have added initial page structure in #187
