### ISSUE TITLE
Landing Page Sections

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#186]
We need a component of a responsive landing page section that can display one of several images (depending on breakpoint) as a background.
Most landing page sections will simply have a background image with a short paragraph of body copy and a heading. All but the FAQ page will be the same height at all times. Some sections (two, thus far) will have an image carousel. Some will have a CTA button that will lead to a different website. There should only be one form input, for the user's email address in the newsletter section. That section also contains social links, a heading, a paragraph and a few spans of text. The FAQ section will have a heading and an accordion with questions and answers. Refer to these mockups for reference.
https://drive.google.com/drive/folders/15bH9XgUA5g6AX6ihZ2x2hKSH-qtNLwao

**Comment by ponderingdemocritus** [comment]
This is looking great! 

This should be straightforward to get up into an initial state.

@RedBeardEth do you see any issues in the mockups?

**Comment by RedBeardEth** [comment]
Nice and clean - no issues that I can see so I will get onto making the repo and components.

It's quite long content form so maybe a sticky nav linking to sections would be helpful

**Comment by Amaro-Koberle** [comment]
> Nice and clean - no issues that I can see so I will get onto making the repo and components.
> 
> It's quite long content form so maybe a sticky nav linking to sections would be helpful

Yes, you're absolutely right. The sticky nav was planned from the start in the wireframe. I didn't make an issue out of it yet because for now, all I needed was a possibility to check how the illustrations work in a responsive format (great work, thank you for this). If you already want to get on it though, eventually we will need it. For now I think the only link we need is the main call to action (as a primary style button) and a logo (icon in mobile format) that links back to the top. If we find it necessary we can add links to each section later. On mobile these would have to go in the burger menu and on desktop they might fit across the top. I think for now though, the call to action will be enough. Later we will add other pages like "how to get started" and things like that.
![image](https://user-images.githubusercontent.com/53105057/179742480-f5b95164-beb8-421f-98fc-d7793dddb125.png)

**Comment by ponderingdemocritus** [comment]
can this be closed?

**Comment by RedBeardEth** [comment]
@Amaro-Koberle  @LordSecretive  is there anything else you would like to add/change before launching?

**Comment by Amaro-Koberle** [comment]
I'd like to change a thousand things, but I think for now this is good
enough for the launch. We'll get back to it in the future. I think this
issue can be closed.

**Comment by LordSecretive** [comment]
Hello github message board.  I didn't know there was a live chat in here until the tag emailed me, apologies

**Comment by LordSecretive** [comment]
is this the current link:

https://realms-landing-page-loot-bibliotheca.vercel.app/

**Comment by ponderingdemocritus** [comment]
closing this now as moving to ship
