### ISSUE TITLE
Realm Details Panel

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#189]
- [x] Keyboard Shortcuts UI
- [ ] Buildings Sidebar
- [x] Responsive design

- [ ] Goblins Sidebar
- [ ] Relic Sidebar
- [x] Raid Panel - undecided whether best to name as "Raid" panel (doesnt make sense if own Realm - and might be best to keep menus same for owned/other realms for keyboard shortcuts etc) - maybe a "Military" panel could work including raid history, defensive/attacking troops, and option to build (if own realm) or raid if settled and not owned. The components required are virtually the same as the Combat panel - so it could be best to share the component (as full screen modal on top of realm detail page)

**Comment by ponderingdemocritus** [comment]
I'm going to take the food panel
