### ISSUE TITLE
Place Link to Desiege S1: Divine Eclipse over the Origin Oasis / Realm

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#19]
There's a Realm [in the Lore](https://docs.loot.foundation/create-and-build-in-the-lootverse/places/divine-city) which contains the Origin Oasis that is said to be where the Divine City hovers over. We should place it on the map.

**Comment by ponderingdemocritus** [comment]
Do you mean to place the actual Divine City on the map? This could be cool. Then you click through to the desiege page

**Comment by micksabox** [comment]
Yes, there should be way to do this. Maybe as a geojson layer?

**Comment by ponderingdemocritus** [comment]
@rvorias This would be the place for the divine portal. Going to assign to you
