### ISSUE TITLE
Combat Panel

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#190]
Discussion in #189 about combining interface with the realm details panel. The combat interfaces will need more scoping as we look to add additional assets into any raiding/battle mechanics

- [x] Better Realm (to raid, and raid with) search (would a more progressive step based interface be more intuitive, e.g 1) select Realm to raid (prefilled if modal coming from realm details or select from lists in #166 or ID) , 2) select your realm 3) raid
- [x] Ability to build troops on attacking Realm
- [x] Add troop image assets
- [x] Raid results display (loading + result interface + add link to get to result from tx sidebar)

**Comment by ponderingdemocritus** [comment]
closing this - will make new
