### ISSUE TITLE
Wallet Connection Z-Index

### ISSUE THREAD

**Issue by micksabox** [BibliothecaForAdventurers/realms-react#193]
**Describe the bug**
When connecting to a wallet, if one of the main tabs is open (Realms, Bank, etc) the wallet modal will appear underneath these tabs and is invisible. 

**To Reproduce**
Steps to reproduce the behavior on ArgentX:
1. Navigate to any tab (Realms for example)
2. Remove local storage key that starts with `gsw-last...` from browser local storage
3. Refresh the page
4. Connect Wallet
 
**Expected behavior**
The wallet  connector select modal should appear.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
If you close the tab and go back to the Atlas map, the wallet connector is visible. Must set the z-index of the wallet connector modal to be above everything else.

**Comment by ponderingdemocritus** [comment]
is this still an issue? I can't reproduce

**Comment by micksabox** [comment]
I don't think this is an issue anymore, will close
