### ISSUE TITLE
Alpha UX improvements

### ISSUE THREAD

**Issue by lordabrax** [BibliothecaForAdventurers/realms-react#196]
- [x] Link doesn't lead to Your Realms tab 
![SEE REALMS.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/25260c41-8032-4eb5-a81e-bfeb93ad4976)

- [x] Player might be confused because no button or instructions indicating the player should approve contracts before Settling 
![Pasted Graphic.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/13cfa81e-97ec-4cd6-8d34-c97bb7fdb3d3)

- [x] Player might be confused becase user sees the button even after approval 
![APPROVE ALL GAME CONTRACTS.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/7487e576-4643-4cb8-94ce-62e3d58ab6f9)

- [ ] Player can accidentally add identical txs and multi-call might fail
![ENQUEUED.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/d317c795-b0f9-495d-88a1-e4453ec6db1b)

- [ ] Player sees broken UI when Indexer is not working
![Pasted Graphic 7.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/eefb2eb0-05c6-4bf0-81d8-93ae86029158)

- [x] Player might not see the progress that owned Realms are Settling 
![SEE REALMS.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/c1b14924-d756-4abe-b68c-9524e3ae9b1d)

- [ ] Player doesn't see anything on a direct link /realms/{} 
![ETERNAL REIGN.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/08c8f1a9-54d5-4cc8-bc61-afdbca643e8e)

- [x] Player might be confused what cross "X" is closing/removing (it closes the whole tab and opens an atlas map)
![Pasted Graphic 10.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/0e377b53-99ce-4faa-99aa-011a588b692b)

- [x] Player will probably miss the popup because it's "black on black"
![Pasted Graphic 12.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/b54fdd4b-b5db-4f48-9d6b-7f2eddbc9ed8)

- [ ] Player might be confused as button near Your LP says "Add+" but the default tab is Swap 
![aidity to the merchant.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/17c55bac-46a0-4c67-97d6-ef0564301024)

- [x] Button can be reduced to a one-liner
![ATTACKING.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/7c1afd6c-bcdd-4f57-87e4-571ea6237705)

- [x] Player doesn't see how many resources are needed
![ARCHER TOWER.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/eceb7f7a-7974-427a-bfd8-634e59c37aae)

- [x] Player might be confused as the game just started but somebody is already starving
![image.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/5349475d-ef49-4617-abe1-c815d9137fef)

- [x] Player might not see this
![CLEAR FILTERS.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/ef95694d-2a23-41df-b72a-6282ad9cc603)

- [x] Player cannot see resources right away (all 0) after reloading a page 
![image.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/1ac252ee-082b-4a17-9e7d-35c80cf32791)

- [x] Player might be confused as non multi-call transactions are hidden in the Status tab by default with no indication that something is working
![image.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/2b612bf4-ca17-4ac5-b415-2f5603fa6f5f)

- [x] Player might not find red and yellow colors to be an intuitive indicator of possibility to create a Building
![image.png](https://images.zenhubusercontent.com/6282cd9a37e2f20c93395301/47a30a06-c39e-4c8a-a1d0-4f61f2a7fb22)

**Comment by ponderingdemocritus** [comment]
- have marked some completed

**Comment by rvorias** [comment]
- [ ] Battle report shows as defense but was actually an successful attack raid ![pillaged](https://user-images.githubusercontent.com/21060408/185376932-0941b065-c0fa-4364-af94-dee0c75f3490.png)
 - [ ] In the train troops sidepanel, when a transaction went into the cart, you cannot click the 'x' button to exit the side panel. Also, the tx cart won't pop-up if you click the tx cart icon. ![train_overlay](https://user-images.githubusercontent.com/21060408/185377553-ef336173-2048-4c43-8501-16cc16639600.png)
