### ISSUE TITLE
AMM Polish

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#199]
**Design and UX**
- [x] Add approx slippage calculation to total lords figure (currently it's too wild)
- [x] Update functions to include tx queue so users can queue up buys/sells with other calls
- [ ] Fix loading flash when adding in value
- [x] Review mobile design to make sure no overflow or weird sizing
- [x] Add fixed height for resource amount cards and fix 'CTA' at bottom of the box. This will allow the user to click the CTA without having to scroll down to the bottom of the list. (Achieve with a flex col and overflow scroll)

**Indexer**
- [x] Cache LP Pools and return value in `useGetExchangeRatesQuery`  @tenoxious  (use `[get_all_currency_reserves](https://github.com/BibliothecaForAdventurers/realms-contracts/blob/feat/amm/contracts/exchange/Exchange_ERC20_1155.cairo#L1009)`)

**Comment by tenoxious** [comment]
@ponderingdemocritus will this require capturing time changes, like rates?

**Comment by ponderingdemocritus** [comment]
it's not really a price change, but it's like LP amount change. So I think it does make sense to track the change over time. In that case we need to capturer both the rate change of token and currency

**Comment by ponderingdemocritus** [comment]
Ui suggestions:

- [ ] Add in 7 day small price chart (like CMC)
- [ ] Add lords Logo next to where LORDS appears (Swap box and other places)
