### ISSUE TITLE
Transaction cart polish 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#200]
- [x] Transaction metadata review across all actions (some are missing metadata)
- [x] Add resources purchased/spent to the tx queue if that transaction is spending. (should be in a small table with the resource icons)
- [x] Icons for the type of transaction - these should appear on the left of the txcart item and give immediate context
- [x] Mobile responsive/styling review - check no overflow etc

**Comment by micksabox** [comment]
Added costs here https://github.com/BibliothecaForAdventurers/realms-react/commit/2ff6320c1e36a66a2e1c51bccdfd9094f941dc97 but still needs work to handle:
- [ ] multiple quantities for buildings
- [ ] some entities also have a Lords cost in addition to resource cost
- [ ] workhut builds need costs to pass in as tx metadata
- [ ] offer option to reconcile any deficits
