### ISSUE TITLE
Adding to favourites show toast

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#208]
- [ ] When adding/removing a Realm to/from your favourites show a toast

**Comment by r0man1337** [comment]
These buttons should have equal functionality?
If so, may be make icons the same?

![image](https://user-images.githubusercontent.com/4090500/187888053-abc190e5-b5e2-40c2-b01d-4b32eb09859c.png)
![image](https://user-images.githubusercontent.com/4090500/187888145-2962c945-449b-4dbe-827d-5a9ff36734a9.png)

**Comment by r0man1337** [comment]
@ponderingdemocritus
