### ISSUE TITLE
Handle incorrect wallet network (L1 & L2 wallets)

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#232]
Users should be informed if they are trying to use an unsupported network with their Web3 connection (e.g having Goerli selected on production when it should be mainnet), and prompted to change to the correct network

**Comment by r0man1337** [comment]
I think we should also add a handle for wallet switch and disconnect button

**Comment by ponderingdemocritus** [comment]
assigning @r0man1337
