### ISSUE TITLE
Argent overrides when signing

### ISSUE THREAD

**Issue by starknetdev** [BibliothecaForAdventurers/realms-react#239]
**Describe the bug**
When signing for commands on atlas argent will always pop up to connect, overriding other providers to sign for the transaction

**To Reproduce**
1. Connect to  Braavos
2. Add Realm to cart on the Empire tab
3. Click the cart (top right)
4. Sign for the command
5. Argent will pop up, asking to connect

**Expected behavior**
Braavos should pop up asking to sign for that transaction

**Screenshots**
<img width="731" alt="Screenshot 2022-10-02 at 22 31 04" src="https://user-images.githubusercontent.com/42612612/193477172-15a06033-7595-43e1-b726-4c6d485c1988.png">

**Desktop (please complete the following information):**

 - OS: iOS
 - Browser: chrome
 - Version: latest

**Comment by RedBeardEth** [comment]
Should be fixed in #241
