### ISSUE TITLE
Modal Minting Bug

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#24]
Model has the last tab autoselected when popup happens. IF the user is not logged in to metamask, the minting button does not work.

Suggestion:
- useEffect calls back to most complete tab on modal load

**Comment by micksabox** [comment]
The modal now intelligently redirects you to either tab 1 if wallet is not connected, tab 3 if StarkNet is not connected, or tab 4 if the user is ready to mint.
