### ISSUE TITLE
AMM: quick add costs request

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#248]
It would be beneficial to have the option to add multiple troop costs with an extra click after selecting the troops.

Eg I need resources for 30x soldiers, so I click soldiers, then enter 30 and then I have the resources populated for 30x soldiers (instead of having to click that 30x times or manually times it by 30.

**Comment by r0man1337** [comment]
Done. Will be added with next PR

**Comment by r0man1337** [comment]
![image](https://user-images.githubusercontent.com/4090500/200657108-ea2f3330-e923-4bad-a782-58a3a5dab6e8.png)

added in commit: d1761a012ef98d4c7407a48bf93385affebe1f68

**Comment by LordSquiddy** [comment]
Perfect, nice work @r0man1337
