### ISSUE TITLE
Fix Approval State

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#253]
<img width="736" alt="Screen Shot 2022-11-07 at 11 18 29 am" src="https://user-images.githubusercontent.com/90423308/200297679-c0fd1336-2002-4c73-a34b-57796249fdde.png">

Fix state for these buttons. The state for the approvals should not refetch on every load.

**Comment by r0man1337** [comment]
@ponderingdemocritus Do you mean save the state for the address in localStorage?

**Comment by r0man1337** [comment]
State variables moved to context in [59bbc0e](https://github.com/BibliothecaForAdventurers/realms-react/commit/59bbc0ec17cf87ef8f77da952dfb8658dcb77d12)
