### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#261]
![image](https://user-images.githubusercontent.com/90423049/203161904-e1f8c6ba-f41e-46f4-be9e-e3a6d9b0b2e7.png)

- [x] Lock orientation and fullscreen (mandatory on mobile?)
- [ ] Application Loader
- [ ] Initial tutorial (save completion status in local storage, or maybe longer term sign a message on completion (or db storage) to prevent reloading (full tutorial pathways can be refined when UI is stable)

**Comment by ponderingdemocritus** [comment]
closing and will create more complete issue with walk through once established
