### ISSUE TITLE
Adding a your Realms cycler in the construct module

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#288]
A quick tool to be able to cycle between your Realms within the construct module for quick and easy empire management

![cycle](https://user-images.githubusercontent.com/91049656/207739662-5f5fb1e5-13dc-4ad8-b433-ae95c8c3e7a7.jpg)

**Comment by ponderingdemocritus** [comment]
dependent on #306

**Comment by ponderingdemocritus** [comment]
#306 is now complete @RedBeardEth 

Please indicate if you can complete in next few days otherwise unassign
