### ISSUE TITLE
Tx Cart issues/suggestions

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#297]
- [x] In the transaction cart when I click on 'see on StarkScan' can that open in new tab please? Otherwise I leave the game, and when I come back the cart status is empty

- [x] #305

- [x] When you go to build a work hut, it says constructing House in Tx Command List, to make clearer would be best if just Work Hut

**Comment by RedBeardEth** [comment]
Work huts deprecated
