### ISSUE TITLE
AMM Issues/Suggestions

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#299]
- [x] The reconcile deficits function is very user-friendly. However, the buying amounts in the buying resources wouldn't clean up after the purchase, which causes the buying amounts to accumulate in the next purchase. I was short of 10 ironwood, but the AMM page suggested I buy 33 Ironwood and 1320 wheat and 1320 fish. (**see img**)

![image](https://user-images.githubusercontent.com/91049656/208027908-78229c9b-8d9b-4f44-806b-23f33f03fd59.png)

- [ ] Indexer is not picking up LP $LORDS transfers

- [x] Make slippage and fee clearer on the AMM

**Comment by Calcutatator** [comment]
Elaboration on slippage issue- 

Bought 1 Dragonhide quoted @ 8.399 $LORDS - Cleared correctly and slippage of less than 1%

https://testnet.starkscan.co/tx/0x629fde359a0575b8d627089ca59cf17c9f66f843f615fa380805dd7bac44dd7

Sold 1 Dragonhide quoted @ 8.35 $LORDS (Higher amount?) - Cleared with a cost of 5.596 $LORDS approx 33% Slippage.

https://testnet.starkscan.co/tx/0x45432eed97823449cffa7283692d65cebbaa46c43c6bcb1b7a06d93635fa1d8

Price impact qouted on both trx 1% within UI

**Comment by Calcutatator** [comment]
### **Sequence issue in regards to balances.**

Will not allow Buy orders in basket unless you have sufficient $Lords balances. Below steps causing error -

1. Queuing several trx within the basket.  Total Lords balance of 145 $Lords.

2. Queued up multiple trx. Buildings, armies etc... Total cost to reconcile balances 250 $Lords. Cannot do as current $Lords balance is too low.

3. Queue up Sell order of resources to sum of 1k $Lords. Should bring total $Lords balance to far more than required. Set this SELL order as trx1 within basket.

4. Attempt to reconcile difference and set BUY order (250 $Lords cost) , unable to set this buy order below the current trx although SELL order should cover this amount. Screenshot below -

<img width="1440" alt="Screenshot 2022-12-19 at 16 54 28" src="https://user-images.githubusercontent.com/114863662/208479456-27b4b2be-db72-4634-9de3-5b22a3dda679.png">

- [ ] Completion

**Comment by r0man1337** [comment]
I took this 
>Sequence issue in regards to balances.

Assigned indexer task to @tenoxious 
> Indexer is not picking up LP $LORDS transfers

and fee/slippage to @ponderingdemocritus 
> Make slippage and fee clearer on the AMM

**Comment by r0man1337** [comment]
Almost complete >Sequence issue in regards to balances. task, but need few more polished with fees and slippage calc to make it work more correct.

**Comment by ponderingdemocritus** [comment]
have made slippage clearer

**Comment by ponderingdemocritus** [comment]
#323
