### ISSUE TITLE
Manage Realms Issues/Suggestions

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#300]
- [x] Harvesting food - I've harvested food and resources successfully on my realm 122. But for the past few hours it has shown food harvests are available, I sign the TX and it completes successfully, but no food is added and the UI still shows harvests available. Harvest TX: https://testnet.starkscan.co/tx/0x231a8245a211d4f8f7ed10679b49c91df42b1ca7a6f58f745ba0e56c9c672ea (the screenshot above is several minutes after the TX above was accepted to L2)

![image](https://user-images.githubusercontent.com/91049656/208028069-e18df9e2-441a-4767-8d97-8340ca145e8f.png)

- [x] Construct farm - When clearing the default max build of farms/fishing villages, once you backspace/clear it, it takes you back to the landing page

- [x] Storehouse - After adding food to my storehouse, the building sqm went to 15 significant digits. Perhaps should limit to 2 decimals

![image](https://user-images.githubusercontent.com/91049656/208028127-897fbdc2-722e-4ad2-b623-f57991f974ac.png)

**Comment by ponderingdemocritus** [comment]
im going to take this

**Comment by ponderingdemocritus** [comment]
all resolved in #308
