### ISSUE TITLE
Raiding Issues/Suggestions

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#301]
- [ ] Would it be possible to setup pings for raiding report to verified wallet owner?
- [x] Add a click on that to bring up modal of defending army composition (I dont think theres a way to see in frontend currently unless you have an army there)

- [x] I have an army at realm 29. The Atlas says there is no defending army but when I click to raid a defending army is there
![image](https://user-images.githubusercontent.com/91049656/208028277-a83767bf-f858-4156-9ab5-1d2a7c62d8e1.png)
![image](https://user-images.githubusercontent.com/91049656/208028332-bf8273f3-1989-4462-ba0c-8c1782b6fc94.png)

- [x] Battle Report - At first I wasn't sure if I won. Suggest changing the battle report title to- Battle Report: Victory! -or- Battle Report: Defeat!
- [ ] 
![image](https://user-images.githubusercontent.com/91049656/208028367-8b4a481d-7d30-4a69-b473-70fa0b1c493e.png)

**Comment by ponderingdemocritus** [comment]
closing and moving final issue into other issue
