### ISSUE TITLE
Trying to push through 70 commands, think its timing out, dont seem to be getting an errors as im not continuously checking, I come back to it and its just still sitting there in the command list and nothing is indicated on argent x window

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#305]

**Comment by RedBeardEth** [comment]
This probably requires a few external dependencies to improve - I would suggest we reassess closer to launch and can do analysis of safe number of commands in a multicall, and break the command list into chunks

**Comment by ponderingdemocritus** [comment]
add to backlog

**Comment by ponderingdemocritus** [comment]
I think we put a hard cap as a temp solution - maybe 50 txs - these seem to process for me
