### ISSUE TITLE
feat: improve Vizir search

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#310]
Right now Vizir is too overloaded with events that they are not useful for the player.

I propose we add buttons above the current vizir feed which allow you to toggle the event type.

This can be done via the `useGetAccountQuery` parsing in the correct vars.

- [ ] Add in Query selector and buttons
- [ ] Add in pagination on the events

**Comment by RedBeardEth** [comment]
I think this is probably better achieved using `getRealmHistory` and `groupByRealmHistory` for much better filtering support

**Comment by ponderingdemocritus** [comment]
so no aggregate reports?

**Comment by RedBeardEth** [comment]
By aggregate reports you mean the `ownedRealmsCount` and `settledRealmsCount` in the `getAccount` query? This should come from the user realms context in #306 (and is not relevant to action of fetching history - so I don't think they need to be linked in a query)

**Comment by ponderingdemocritus** [comment]
ok - so you suggest just using the state of the realms and manipulating that object to get the history for each realm, rather than a wallet query?

**Comment by RedBeardEth** [comment]
I'm not quite sure I'm following - the `useGetAccountQuery` is just ` accountHistory: getRealmHistory(filter: { realmId: { in: $realmIds } }) {` - but we have a far more descriptive query in:

 `useGetRealmHistory` = `  getRealmHistory(filter: $filter, take: $take, skip: $skip) {` 

This allows for pagination, filtering by event type/realm/owner etc

**Comment by ponderingdemocritus** [comment]
yeah ok, understood - i think you should take this then

**Comment by ponderingdemocritus** [comment]
connect to #212 have assigned @RedBeardEth

**Comment by ponderingdemocritus** [comment]
assigned to @r0man1337

**Comment by ponderingdemocritus** [comment]
#343
