### ISSUE TITLE
AMM Issues/Suggestions #2

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaForAdventurers/realms-react#313]
- [ ] More information on AMM - I provided LP for the Gold/LORDS market, but don't have much insight into how that position is doing. Would love to see my earned fees, my % of total pool LP, etc 
- [x] When removing LP it would be great if I could click my LP and have that number populate in the remove field
- [ ] User flow - Reconciling balances should not have to go into the AMM. Combine the reconciling differences in a sum when signing transaction - Quote the $LORDS amount and transact with the AMM without having to. go into the AMM 
- [x] Max sellable units are only 7 digits long. When selling wheat or fish usually is in 8+ digits. Can unit max be increase?

**Comment by ponderingdemocritus** [comment]
We are going to have to index the value of Currency and value of Token at the time of adding the LP position @tenoxious 

If we do this then we will be able to show the difference in LP growth from time added to now. We can add this into the backlog as it is rather involved.
