### ISSUE TITLE
Travel UI Issues

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#315]
- [x] Lines for travel do not disappear until you refresh the browser -
![image](https://user-images.githubusercontent.com/114863662/209441333-da90fe59-0109-41e6-8d0d-9f82d5e6924a.png)

- [x] Travel lines on the map are not accurately indicating the position the army is traveling to. See below example, blue circles are the start and end point of the lines. Top right is where the line animation ends -
![image (1)](https://user-images.githubusercontent.com/114863662/209441363-0d2d1743-fab3-487a-9904-c229d5944498.png)

**Comment by ponderingdemocritus** [comment]
fixed in #323
