### ISSUE TITLE
Farming Feature Requests

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#317]
- [ ] (REQUEST 1) Better explanation of Farming process short term and made more intuitive long term.

I think we need to rework the flow for building farms,  having a queue up functionality seems kind of odd if building new farms and fisheries removes all benefit from existing ones.

If it is too computationally more difficult, a simpler version would be better than the current system if too expensive to do
Especially confusing for the player because there is a count of how many harvest left per farm displayed in the UI.

Leading one to believe that is a number being tracked based on the farms built and harvested, not all farms.

I don’t actually know how much more expensive it would be, as I haven’t measured/calculated it. I agree that if not reworked, it should be explained more clearly. 

Relevant Conversation : [link](https://discord.com/channels/884211910222970891/1007536317334298705/1053707938226782218)
---------------------------------------------------------------------------------------------------------------------------------------------------

- [ ] (REQUEST 2) Quality of life updates for building Farms

The max number of farms I can build on my realm is being set by default. would be less of a shell shock to users if that was set to 1 by default. The amount of resources needed and I was thinking to myself why do I need 190 wood to build one farm? 

The should be a preference toggle allowing for diff bulk operations (store X million fish/wheat in warehouse, store XY million fish/wheat) and same for farms/fisheries/workhuts. Toggle as build 1, build 5, build max. 

Relevant Conversation : [link](https://discord.com/channels/884211910222970891/1032061770627563560/1053765592131325982)

**Comment by ponderingdemocritus** [comment]
I we are rethinking farms - standby

**Comment by Calcutatator** [comment]
Closing as irrelevant with new updates
