### ISSUE TITLE
UI Issue - Raidable Realms not showing

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#318]
- [x] Filtering to "Raidable" realms on the atlas does not show the realms that are raidable only non-raidable realms. 

![image](https://user-images.githubusercontent.com/114863662/209585166-77e2ed5c-c6d1-4c79-815c-b128b637c969.png)

**Comment by Calcutatator** [comment]
@ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
We need to now search through all the Balances of the resources generated - then return asc order of these.

@tenoxious you have a good understanding of what needs to be done?

**Comment by ponderingdemocritus** [comment]
have added a basic filter in #327 

You can now filter by raidable but it does not order them by total amount - this might require a bit more thought, but it is an improvement over what currently exists
