### ISSUE TITLE
Armies not showing as on a Realm and unable to raid

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#322]
After the recent Resource update some armies are no longer showing as able to raid certain Realms.

- [x] Realm Muki Kaki is showing as having a radiable vault. The Realm is annexed by several armies but none are able to raid, the box is greyed out.

![image](https://user-images.githubusercontent.com/114863662/211224230-4b183f58-5d1d-4e94-ad75-06f038f1489d.png)

- [x] Armies at the Realm Muki Kaki are showing as annexing the realm under the "My Armies" tab but are not showing as at the realm when inspecting Muki Kaki directly.

![image (2)](https://user-images.githubusercontent.com/114863662/211224154-19ba74b8-6319-471c-a457-15f3d45e9a35.png)

**Comment by ponderingdemocritus** [comment]
#323
