### ISSUE TITLE
Unable to choose armies to raid

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#324]
The is currently no way to choose which army attacks if you have multiple armies annexing a realm. 

- [ ] A toggle or button to choose which to utilise would be perfect.

Example -
![image (1)](https://user-images.githubusercontent.com/114863662/211636403-bb22ccc9-dc31-43b5-a717-9dc4dba80a76.png)

**Comment by ponderingdemocritus** [comment]
make scroller underneath own realm

**Comment by ponderingdemocritus** [comment]
#327
