### ISSUE TITLE
Error on impact of AMM 

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#325]
- [ ] Getting the below error when trying to buy some Mythril. Price impact is showing as low so should be fine, tried with various 3 digit amounts of Mythril and none seem to work.

**Set up when actioning -**
![image (3)](https://user-images.githubusercontent.com/114863662/211642647-e754f9d6-63b9-4f13-b413-fdb5ebe708d1.png)

**Error -**
Error in the called contract (0x42bf805eb946855cc55b1321a86cd4ece9904b2d15f50c47439af3166c7c5e2):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x42bf805eb946855cc55b1321a86cd4ece9904b2d15f50c47439af3166c7c5e2):
Error at pc=0:24:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:3554)
Error message: Maximum currency amount exceeded
Unknown location (pc=0:3501)

Traceback (most recent call last):
  File "<hint4>", line 3, in <module>
AssertionError: assert_not_zero failed: 0 = 0

**Comment by Calcutatator** [comment]
@ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
this should be fixed
