### ISSUE TITLE
Giving a home to the chat button

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#328]
The chat button is awkwardly floating in the bottom right corner. I drew a place for it in the top left portion of the frame. Could we move it there?

**Comment by Amaro-Koberle** [comment]
![Image](https://user-images.githubusercontent.com/53105057/212471778-be7f2e19-2f3a-4404-ac2f-dd47caf7d35a.png)



![Image](https://user-images.githubusercontent.com/53105057/212471785-6877f3cf-79c0-46ae-830b-c2adcdd764be.png)

The corner is also occupied by a matchbox logo. I guess we'll ignore for now, but I'll consider adjusting the frame to cover that logo up... not sure.

**Comment by Amaro-Koberle** [comment]
https://drive.google.com/drive/folders/1ZX95b7iG2wtc6FhNwe1jXYhl4feh17h2

I also made an icon for it. I admit, it's pretty sloppy right now, but it does fit more with the style as a placeholder for now.

In terms of color, could it please be gold?

**Comment by ponderingdemocritus** [comment]
on this

**Comment by ponderingdemocritus** [comment]
#327
