### ISSUE TITLE
We need a vignette in the frame!

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#329]

**Comment by Amaro-Koberle** [comment]
There are some visual issues with bright map items around the edge of the frame.



![Image](https://user-images.githubusercontent.com/53105057/212472193-5e4e825a-68a0-419f-82a0-db7a6361cff8.png)

This doesn't read.
A quick solution would be a vignette... I suggest we add it underneath the frame, above the map.



![Image](https://user-images.githubusercontent.com/53105057/212472241-ec036925-5ec1-4bdc-819e-b99027cb658e.png)

Just an html element with some blurred dark border or however one makes a vignette in CSS/Tailwind. Would be preferable if it was a dark brown Something like Hex #5F3100 color. Would also be preferable if it was in multiply blend mode rather than normal. There's some tailwind filter for this, I think.

**Comment by ponderingdemocritus** [comment]
Ill do a pass on this and setup some variables
