### ISSUE TITLE
Raidable vaults not giving resources on Victory

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaForAdventurers/realms-react#330]
- [ ] Raiding is not outputting resources to the victors unless the raidable amount is greater than 25 per resource.

Raiding the below realm output 0 resources although winning. The resources in this realms vault shown all where under 25.
![image (1)](https://user-images.githubusercontent.com/114863662/212541087-ec45c4bc-023e-45cd-836e-eb2810f930d7.png)

**Comment by ponderingdemocritus** [comment]
should we allow this? Maybe there should be a minimum
