### ISSUE TITLE
Harvest action yields weird "undefined" title in decree panel.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#332]
![image](https://user-images.githubusercontent.com/53105057/212631135-a7a7ad30-8127-4d96-8401-222e4a540359.png)
When clicking the harvest button, the tx added to the decree panel reads undefined. I assume that is not intentional.

![image](https://user-images.githubusercontent.com/53105057/212631293-ac230689-3cab-46a8-a7c9-0cfce1a89bcf.png)

It's not a major thing, the tx went through anyway. Just thought I should mention.

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/212631639-9aa0b4a9-3011-43a9-8847-57649f56a7ad.png)
 There's a missing image there too

**Comment by r0man1337** [comment]
Fixed
