### ISSUE TITLE
The UI let's me attempt to sell more resources then I have

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#335]
![image](https://user-images.githubusercontent.com/53105057/212668589-1ea7729d-4b1e-48ac-af00-3d6619782ba1.png)

The "Sign For 1 Command" button should be disabled... additionally, the AMM shouldn't let me add that transaction in the first place, right? We should alert the player ASAP that he's attempting an impossible thing.

**Comment by Amaro-Koberle** [comment]
Ah... actually. I am realising that the "Available resources" tooltip smartly subtracts the amount being sold via the decree panel. However, in that case it's worse... I did have enough obsidian to sell but the transaction still fails.

Here is the error:
```
Error in the called contract (0x42bf805eb946855cc55b1321a86cd4ece9904b2d15f50c47439af3166c7c5e2):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x42bf805eb946855cc55b1321a86cd4ece9904b2d15f50c47439af3166c7c5e2):
Error at pc=0:24:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:3831)
Error message: Below minimum currency amount
Unknown location (pc=0:3778)

Traceback (most recent call last):
  File "<hint4>", line 3, in <module>
AssertionError: assert_not_zero failed: 0 = 0.
```

**Comment by ponderingdemocritus** [comment]
This is a slippage error - on my list of things
