### ISSUE TITLE
Move the decree panel button (currently the bibliotheca icon in the top right) to where the vizier PFP is (in the bottom left, which currently does nothing).

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#340]

**Comment by ponderingdemocritus** [comment]
II disagree with this tbh - naturally, our eyes move to the top right corner - so the action we click the most should be there IMO. And in our case the tx cart is crucial part of the UI

**Comment by Amaro-Koberle** [comment]
Absolutely agreed that the tx cart is crucial. Not sure about our eyes traveling naturally to the top right. The composition of the frame is laid out such that most of the emphasis is on a left-hand bar (as is quite common in many web apps). I did consider making a top emphasised version, but that was generally less well received when I asked on Twitter. I actually think this makes sense, focusing on the left hand side looks better.

@ponderingdemocritus How about this: We move the tx-cart to the top-right (where the empire page now is, arguably the most dominant place in the UI), and move the empire page down where the image of the vizier sits (this would make thematic sense because the vizir is displayed on that page). I think that might actually be the best solution.

What I think we should definitely avoid:
Right now, the (in my opinion) second most visually dominant spot in the UI (the little PFP image) does absolutely nil when clicked. That is a waste of prime UI real-estate, I hope you'll agree.

**Comment by ponderingdemocritus** [comment]
- have made teh bottom left guy clickable to open vizir search for now
