### ISSUE TITLE
Update the search bar to be a bit more subtle (I made some new SVGs) and move the atlas button.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#341]
![Image](https://user-images.githubusercontent.com/53105057/212983732-70665c9a-de90-4193-bae4-26a71e36659b.png)

https://www.figma.com/file/BNxiYPgG7l5ZxO7JXYGdJ0/Print-Design-System?node-id=0%3A1&t=Nt3uL2EJf9iYft7n-0

https://drive.google.com/drive/folders/1ZX95b7iG2wtc6FhNwe1jXYhl4feh17h2

I would like to move the atlas button next to the searchbar (where the biblio logo used to be). The vizier PFP in the bottom left od the frame should function as the link to the decree panel. I want to separate the atlas button because it is mainly about navigation in the UI and less about a specific feature like the other buttons in the manu bar on the left. Hope makes sense.

**Comment by ponderingdemocritus** [comment]
#343
