### ISSUE TITLE
feat: move images to cdn

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#346]
Move images and assets to CDN or similar

This will improve performance

**Comment by RedBeardEth** [comment]
@ponderingdemocritus Images should already be served from a CDN (Vercel's edge network) - I have noticed quite a few <img> tags being used around the place which are not optimized so I will go through and audit - but in general these should be using the next/image component unless I'm missing something

**Comment by ponderingdemocritus** [comment]
so any Image that is in the repo will be added to the network?

**Comment by RedBeardEth** [comment]
Using the next/image <Image> component (and auto-optimized) yes.

You can verify by checking the console network image response's x-vercel-id - the first three letters of which should be data center id close to your location

**Comment by ponderingdemocritus** [comment]
ok closing this
