### ISSUE TITLE
feat: tab borders

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#347]
![image](https://user-images.githubusercontent.com/53105057/213255199-27944ca5-3e13-4f06-b453-45b0646c9d9a.png)

So right now the tab groups read like primary buttons. I think that should be avoided. I made some alternatives.

You can find the SVGs here:
https://drive.google.com/drive/folders/1ZX95b7iG2wtc6FhNwe1jXYhl4feh17h2

And the figma here:
https://www.figma.com/file/BNxiYPgG7l5ZxO7JXYGdJ0/Print-Design-System?node-id=0%3A1&t=iJM8fIbeJfXqS76C-0

**Comment by r0man1337** [comment]
done in #376
