### ISSUE TITLE
feat: Mobile readiness

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#348]
Compatability with landscape mode on phones and Braavos.

**Comment by Amaro-Koberle** [comment]
Yeeeess!! I wasn't going to push too hard for this yet but honestly it'll be great to have it work on mobile, at least decently well.

**Comment by r0man1337** [comment]
- [x] 1. Buildings construction tab
- [x] 2. Army construction tab
- [x] 3. Labor Table small fixes
- [x] 4. Realm overview tab small fixes
- [x] 5. AMM make blurred bar more compact
- [x] 6. Lore small fixes (margins and paddings)
- [x] 7. Leaderboard small fixes 
- [x] 8. Make main UI border smaller

**Comment by r0man1337** [comment]
done in #467
