### ISSUE TITLE
Adjusting the colors in the frame

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#349]
Remove the beige elongated pill shape underneath the main nav icons.
Turn all clickable things golden. The rule is this: If the user can click it, it's golden. If not, then not.

**Comment by Amaro-Koberle** [comment]
Things that are beige even though they should be gold:
![image](https://user-images.githubusercontent.com/53105057/213648610-e14127f2-fcb6-4d76-b6ed-be39c612b96b.png)
![image](https://user-images.githubusercontent.com/53105057/213648638-d8f70e61-1339-43b8-aa9c-1f42e3a9e5d0.png)
![image](https://user-images.githubusercontent.com/53105057/213648683-cb42bf65-899f-4bcd-90a3-9955c5094d27.png)
![image](https://user-images.githubusercontent.com/53105057/213648721-ac3402f5-6849-4aa4-ba27-5d3064e98453.png)

Remove the background element on these and turn them golden:
![image](https://user-images.githubusercontent.com/53105057/213648806-6f17c06e-4104-459d-b5f5-a9078dd0ff44.png)


Refer to the figma:
https://www.figma.com/file/BNxiYPgG7l5ZxO7JXYGdJ0/Print-Design-System?node-id=0%3A1&t=hxMhBeZdeboAWYXf-0

**Comment by ponderingdemocritus** [comment]
#343
