### ISSUE TITLE
We need the exit button back!

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#358]
![image](https://user-images.githubusercontent.com/53105057/213937160-acbb9136-6c05-45a4-b41b-2b1f74e6b6da.png)

Great work @r0man1337, looks really good. All that is missing urgently is the exit button.
I made some SVGs and updated the figma file

![image](https://user-images.githubusercontent.com/53105057/213937651-9b2e7fd6-654b-4ff2-9a78-616ddf25c70c.png)
https://www.figma.com/file/BNxiYPgG7l5ZxO7JXYGdJ0/Print-Design-System?node-id=0%3A1&t=RxZ9PMqEJ3KyLF68-0

https://drive.google.com/drive/folders/1SjhdqCFpd8aX4cWUuBwHNWcPVdJysCS6

**Comment by r0man1337** [comment]
done in #372
