### ISSUE TITLE
can click the harvest button an arbitrary amount of times

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#361]
![Image](https://user-images.githubusercontent.com/53105057/214046617-3d0ce67d-21ff-4322-bbcc-f1aab8a642db.png)

The harvest button needs to be disabled after clicking it once, otherwise it let's me add a bunch of identical transactions into the decree panel. Apart from disabling the button, I think the decree panel should never even accept a transaction that it already contains.

![Image](https://user-images.githubusercontent.com/53105057/214046943-f6823ba7-ccb0-4b0e-bde4-cc9dad384d09.png)

**Comment by ponderingdemocritus** [comment]
ill fix this

**Comment by ponderingdemocritus** [comment]
#371
