### ISSUE TITLE
Numbers are way too high for food.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#364]
![Image](https://user-images.githubusercontent.com/53105057/214049115-42699599-f49d-470e-a342-261e0f80084b.png)

The time remaining should be given in hours and one unit of food should be at least a thousand times larger. When have you last thought about food of a quantity lower than 1000 while playing Eternum?

**Comment by ponderingdemocritus** [comment]
can't change this easily 

I have made a function to at a 'k' when numbers over 1k
