### ISSUE TITLE
I haven't been incurring any losses in combat twice in a row, the first time I had even lost. Is that supposed to be that way?

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#366]
![Image](https://user-images.githubusercontent.com/53105057/214346915-635031d8-424a-44de-b40d-a98a42778e68.png)

The flavour text (which is too long btw, we should keep it below three lines max) is telling me that heavy losses occured, but the table below doesn't register any losses.

**Comment by ponderingdemocritus** [comment]
got it
