### ISSUE TITLE
Removing LP 'Total Lords Received' Issue

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#368]
When removing LP from the AMM, Total Lords Received field displays an unknown value.

The user enters the amount of LP they wish to remove from the AMM, and the $LORDS and resource quantities they will receive are correctly displayed. In the case below 39.868 LP is removed for 30.777 $LORDS and 368.036 Gold. Unclear what the 3.485 value is for Total Lords Received.

<img width="536" alt="lp" src="https://user-images.githubusercontent.com/42439169/214462462-aaec4530-cdc0-4bcf-8ec7-8380acdcc4c0.png">

**To Reproduce**
1. Go to the AMM and add liquidity, then remove it
2. Correct $LORDS and resource values will be displayed, but unknown Total Lords Received value

**Expected behavior**
Specify what this value is (accumulated fees?) or remove from display.

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version: 109.0.5414.119

**Comment by ponderingdemocritus** [comment]
Ty - have identified.

The issue is that the value is being pulled as the purchase price - not the LP amount. This is a client view error
