### ISSUE TITLE
Travel estimate differs from actual

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#370]
When selecting an army to travel to a realm, a time estimate is given for when the army will arrive. This estimate differs from the actual travel time once the transaction has been mined.

Expected behavior: estimate and actual travel time should match.

Estimate:
<img width="490" alt="estimate" src="https://user-images.githubusercontent.com/42439169/214698524-a717f9d0-d441-4d14-a5cb-21484e8bacd3.png">

Actual:
<img width="426" alt="actual" src="https://user-images.githubusercontent.com/42439169/214698543-356e9583-6c90-41f5-8fa9-3f98f7391f16.png">

**Comment by palomato** [comment]
Could it be the Estimated travel time is from the realm id the army was created on, instead of the realm id of the army's current location? (or vice versa) Another example:

Estimate:
<img width="554" alt="travel1" src="https://user-images.githubusercontent.com/42439169/215014208-d199b50f-3507-4a0d-81d8-8d11e61f8ad5.png">

Actual:
<img width="435" alt="travel2" src="https://user-images.githubusercontent.com/42439169/215014253-2c75d199-bdfd-4e85-9d3e-78d7985eba70.png">

**Comment by ponderingdemocritus** [comment]
This is travel bug in contracts, which has been fixed
