### ISSUE TITLE
Reconcile Deficits should default AMM toggle to BUY

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#377]
Clicking 'Reconcile Deficits' in the transaction cart takes players to the AMM with resources/quantities populated. But the Buy/Sell toggle is set to whatever the player last did on the AMM. For example:

Action 1: sell resources on the AMM
Action 2: buy <anything> and click Reconcile Deficits

The correct resources/quantities populate, but the toggle is still set to Sell. 
Expected behavior: toggle always sets to Buy when clicking 'Reconcile Deficits'

<img width="557" alt="1" src="https://user-images.githubusercontent.com/42439169/214950162-5adb7688-1c55-45e7-adf7-7ed0d0d4e8fa.png">
<img width="554" alt="2" src="https://user-images.githubusercontent.com/42439169/214950168-2f737878-6427-4a60-8001-cb9e9d04dbef.png">

**Comment by r0man1337** [comment]
fixed in #376
