### ISSUE TITLE
TX Cart Saved After Logout, Browser Refresh etc.

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#380]
TX Cart is erased after logout, browser refresh etc. Normally not much of an issue but I could see some frustrating instances if you accidentally refresh after creating a thorough order of actions.

Could be nice if the tx are saved the next time you login in these instances.

Probably pretty low priority.

**Comment by r0man1337** [comment]
It should erase only one time (quick-fix for saved transactions with old metadata format). Can you check?

**Comment by r0man1337** [comment]
Implemented in #432

**Comment by ponderingdemocritus** [comment]
If this get's implemented it should have an expiry of a week max and should have a limit of storage maybe 60 txs
