### ISSUE TITLE
Atlas Standard Views and Zooming

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#381]
1. Remove the auto zoom when you select a realm, it takes quite a while but even if it was instant you might want to quickly see details of multiple realms that are across the map. Maybe double click for zoom.

2. When you click the globe that takes you to the atlas it would be nice to have it take you to a preset zoom that allows you to see the entire globe if you’re already on the atlas. Maybe one click to atlas, double click for an entire world view.

**Comment by ponderingdemocritus** [comment]
added both features - good option - the client too slow for the transitions
