### ISSUE TITLE
Mouse & Touchpad Zooming

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#382]
MacBook Pro 14 Inch 2021 Apple M1 Pro 16GB macOS Monterrey 12.1

Brave Browser, windowed mode, Braavos wallet

Zooming out with mouse scroll never works consistently. It stutters and refuses to zoom in or out but then seemingly randomly works. My touch pad  also no longer works to zoom. Double click to zoom does work, but then I have no option to zoom out other than clicking on a realm.

**Comment by palomato** [comment]
@gogibear try double-tapping the touchpad, but on the 2nd tap hold your finger against the pad and try sliding it down to zoom out, up to zoom in

Not a solution, but works for me on some apps

**Comment by r0man1337** [comment]
I have the same issue, still not figured out how to fix this. May be add zoom controls as workaround

**Comment by ponderingdemocritus** [comment]
known issue with mapbox - will be fixed with #408
