### ISSUE TITLE
Missing Spaces in Building Names

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#383]
Missing spaces between the building names when you go to bank and buildings.

-FishingVillage
-ArcherTower
-MageTower

<img width="496" alt="Screen Shot 2023-01-26 at 3 36 05 PM" src="https://user-images.githubusercontent.com/102257289/214974373-8143919c-9730-4e7b-8afa-fe2b35b911ac.png">

**Comment by ponderingdemocritus** [comment]
fixed
