### ISSUE TITLE
Add 'Maximum 100' to adding resources for troops at bank

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#385]
Could add ‘Max 100’ on the bottom of this screen. Just in case you’re trying to buy max armies for 5+ realms. I didn’t realize my 1000 adds weren’t being logged at first.

<img width="308" alt="Screen Shot 2023-01-26 at 3 42 41 PM" src="https://user-images.githubusercontent.com/102257289/214975160-5843ce37-715b-4196-9349-04092b687146.png">

**Comment by ponderingdemocritus** [comment]
#391
