### ISSUE TITLE
Spelling Error in Army Statistics in Army Travel Screen

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#386]
When you are at the Travel Army screen and hover over the shield icon your list of units has two errors:

1. Longbow -> Hunter
2. Solider -> Soldier

Also could keep the unit number the same either make them all plural with 's' or singular without it.

<img width="563" alt="Screen Shot 2023-01-26 at 3 47 33 PM" src="https://user-images.githubusercontent.com/102257289/214975827-20090f13-3bc7-4a25-afa2-fdc09617dc70.png">

**Comment by ponderingdemocritus** [comment]
#391
