### ISSUE TITLE
Personal Relic State + Number of Captured Relics

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#387]
Split up this info a bit:

[ Annexed / Sovereign ] 
[ Conquests: # (icon) ] 

<img width="324" alt="Screen Shot 2023-01-26 at 3 52 38 PM" src="https://user-images.githubusercontent.com/102257289/214976481-61eaec91-72d1-46b5-9f62-25e3bb866669.png">

**Comment by ponderingdemocritus** [comment]
adjusted in #391
