### ISSUE TITLE
Bug: battalion details cutoff on travel screen

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#388]
Players can hover over their armies when selecting an army to travel. Normally troop types are shown in the popup, but now appear cutoff.

Expected behavior: hovering over an army displays troop types

To recreate: Select a realm in the Atlas and click Travel to Raid. Hover over your armies and you will see the popup is cutoff.

<img width="552" alt="army_details" src="https://user-images.githubusercontent.com/42439169/214998146-40c9d809-3f39-4f9d-83ed-eaa47efede1e.png">

**Comment by ponderingdemocritus** [comment]
added min heigh of box to fix in #391
