### ISSUE TITLE
Bug: harvest button does not dim for Wheat & Fish

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#389]
In the Empire page -> Quick Actions tab, harvesting a resource dims the Harvest button and clicking it again does nothing. But the Harvest button does not dim for Wheat and Fish, and the player can continue to hit Harvest and add harvest transactions to their cart.

Expected behavior: After clicking Harvest on Wheat or Fish, Harvest button should dim and clicking it again should not add more transactions to the cart.

Reproduce behavior: Produce Wheat or Fish and attempt to harvest via the Quick Actions tab.

<img width="678" alt="farm_button" src="https://user-images.githubusercontent.com/42439169/215001519-92e3c9fa-d8ba-48ba-836c-2d3ad816438e.png">

**Comment by ponderingdemocritus** [comment]
#391
