### ISSUE TITLE
Shield / Attack do not have selected styling

### ISSUE THREAD

**Issue by rvorias** [BibliothecaForAdventurers/realms-react#39]
The user can not see which button is selected.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/21060408/155417235-00afb50d-9046-4052-a6b2-5f9263569281.png">

**Comment by micksabox** [comment]
This was caused due to the game controls displaying before the game context was fully loaded. This was fixed [here](https://github.com/BibliothecaForAdventurers/realms-react/commit/8e8fa10ae0c260b6319183ec770debca049a1b4d), will close this issue.
