### ISSUE TITLE
Feat: interesting army movement lines

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#390]
When an army is traveling red lines are drawn from its origin to its destination. Then the lines disappear and the animation begins again. Clicking or hovering over the lines does nothing.

![Picture1](https://user-images.githubusercontent.com/42439169/215004077-9e9252f7-a79e-480b-9724-fc7f5beda59e.png)

Suggestion: Use an opaque line and have the animation run through it from origin to destination. The animation might look similar to a heartbeat monitor.

![pulse](https://user-images.githubusercontent.com/42439169/215004474-5017aa72-1fc3-4ff1-b108-5f46ae9c6453.gif)

Lines could all be the same color to signify 'this is an army movement,' but perhaps the 'pulse' traveling through the line is the attacking army's Order color. Hovering over the line could reveal a popup with the army origin, destination and troop composition. This will give the Atlas more utility.

Allow the user to on/off toggle army movement lines so the Atlas never gets too cluttered.

**Comment by ponderingdemocritus** [comment]
have made the lines more transparent and fade.

will need to experiment with more

**Comment by ponderingdemocritus** [comment]
this will be done in #408 

closing this
