### ISSUE TITLE
Bug: army travel draws horizontal lines

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#392]
When a traveling army crosses the eastern or western edge of the atlas, the path becomes a straight line across the top of the atlas and resumes on the opposite side.

Expected behavior: Arched lines of travel that exit one side of the map and reappear on the other.

<img width="1903" alt="lines" src="https://user-images.githubusercontent.com/42439169/215015180-483a0882-31fb-4bb0-9814-56fafb82d3ce.png">

**Comment by ponderingdemocritus** [comment]
will be fixed in #408
