### ISSUE TITLE
Bug: army travel times disappeared

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#397]
*This is for armies that are currently traveling*
UI used to display time until armies reached their destinations, but now missing.

Expected behavior: UI displays time until army arrives at destination.

Reproduce: Travel an army then check My Armies tab

Empire tab -> My Armies
<img width="919" alt="travel1" src="https://user-images.githubusercontent.com/42439169/215205734-98881176-9230-4102-9764-c812728b9b73.png">

Selecting army after clicking 'Travel-to-Raid' button
<img width="550" alt="travel2" src="https://user-images.githubusercontent.com/42439169/215205738-da6e5601-e30c-4b8b-9716-4bea0062af45.png">

**Comment by ponderingdemocritus** [comment]
fixed the first image in new PR 

Please close when confirmed

The times never existed in the 2nd image - there is a time column
