### ISSUE TITLE
Bug: battalion details cutoff on travel screen pt2

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#398]
When selecting an army to travel, players hover over the shield causing a popup with troop composition to appear. The popup is still cut off at the bottom, even after after merging [#391](https://github.com/BibliothecaDAO/realms-react/pull/391)

Looks like the popup is constrained to the 'select army' window, can't popup out of it

Recreate: When selecting an army for travel, hover over the shield

<img width="542" alt="hover" src="https://user-images.githubusercontent.com/42439169/215206580-a21c8ecd-604e-45fd-b26e-6ef47360507e.png">

**Comment by palomato** [comment]
Related Issue [#388](https://github.com/BibliothecaDAO/realms-react/issues/388)

**Comment by ponderingdemocritus** [comment]
can't reproduce on my device - I have implemented a fix that I think it was. Please confirm then close issue

**Comment by palomato** [comment]
If you have many armies then you cannot reproduce issue, because the 'select army' window is large enough to show entire troop composition popup. Show Armies Distance button is far down for you.

Can reproduce if you have only a few armies. Could it be the 'z-index' of army composition popup putting it lower than Show Armies Distance button?

**Comment by palomato** [comment]
<img width="1339" alt="reproduce" src="https://user-images.githubusercontent.com/42439169/215238223-53dea4c0-886e-4ec8-b1ef-5017b29a79d0.png">

**Comment by palomato** [comment]
:point_up_2: can see it cuts off after Archanist, because the window height with 4 armies is not tall enough to fit unit composition popup

**Comment by ponderingdemocritus** [comment]
have attempted a fix - please confirm after the next update

**Comment by palomato** [comment]
Will do

Edit: can do this tmrw (30th)

**Comment by palomato** [comment]
<img width="533" alt="close" src="https://user-images.githubusercontent.com/42439169/215566688-5a028d1b-dae6-4825-98eb-618fa17ae1ef.png">

Issue resolved, even with few armies 👍
