### ISSUE TITLE
Bug: Storing food - burn amount exceeds balance

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#402]
Receive the following wallet error when storing food:

```
Cairo traceback (most recent call last):
Unknown location (pc=0:2600)
Unknown location (pc=0:2586)
Error message: ERC1155: burn amount exceeds balance
Unknown location (pc=0:1597)
```

The action to store food is the only action in the transaction cart, and no pending TXs.

To Reproduce: Empire page -> Food tab and select 'All' button to store all Wheat. Click 'Store' button and sign TX in wallet to receive error message.

_Note: I can reduce the quantity of food to store, say to half, and the transaction completes without error._

Action: Click All then Store
<img width="428" alt="food" src="https://user-images.githubusercontent.com/42439169/215278689-a2858912-e822-44d8-b9e1-da72d18cfe78.png">

Action: Sign transaction results in error
<img width="277" alt="overflow" src="https://user-images.githubusercontent.com/42439169/215278841-d94b5b41-591f-48f4-b7ac-32dae58f81da.png">

Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:228)
Unknown location (pc=0:214)

Error in the called contract (0x90ec9ba85d7f0c00327c5ce434d3174756ceb916f7b581a0b28041dc73a851):
Error at pc=0:208:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:4056)
Unknown location (pc=0:4004)
Unknown location (pc=0:3090)
Unknown location (pc=0:3111)

Error in the called contract (0x2d73a83afeaf5927c2dfb51b2412ea9dfe1fb6cd41b1b702607e7345ce47d09):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x2d73a83afeaf5927c2dfb51b2412ea9dfe1fb6cd41b1b702607e7345ce47d09):
Error at pc=0:175:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:2544)
Unknown location (pc=0:2521)
Unknown location (pc=0:1688)

Error in the called contract (0x7080e87497f82ac814c6eaf91d66ac93672927a8c019014f05eb6d688ebd0fc):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x7080e87497f82ac814c6eaf91d66ac93672927a8c019014f05eb6d688ebd0fc):
Error message: SafeUint256: subtraction overflow
Error at pc=0:937:
An ASSERT_EQ instruction failed: 0 != 1.
Cairo traceback (most recent call last):
Unknown location (pc=0:2600)
Unknown location (pc=0:2586)
Error message: ERC1155: burn amount exceeds balance
Unknown location (pc=0:1597)

**Comment by ponderingdemocritus** [comment]
I think this might have been due to previously added food and the local food value not updating. If you have no pending txs and you add all your food supply then you shouldn't get an error.

**Comment by ponderingdemocritus** [comment]
can you try and reproduce and check

**Comment by palomato** [comment]
<img width="428" alt="storehouse" src="https://user-images.githubusercontent.com/42439169/215371483-1d4d8441-be65-4873-b8ab-9e54853fd4ae.png">

I'm able to reproduce. Selecting 'All' and 'Store' gives me the same error shown above. No pending transactions when I attempted this.
```
Error message: ERC1155: burn amount exceeds balance
```

**Comment by palomato** [comment]
Only occurs with Wheat. No problems with Fish--can select 'All' with Fish and transaction successful

**Comment by Fomentador** [comment]
I get a similar "burn amount exceeds balance" error when trying to build a military building and summon respective armies in the same transaction. Four transactions in queue: Reconcile (I have enough Lords to buy the resources); Build Archer Tower; summon a new attacking army with 5 Archers and 5 Longbows; summon a new defending army with 5 Archers and 5 Longbows. Error below: 

Error in the called contract (0x39f40b33de4d22b2c140fccbcf2092ccc24ebdb7ed985716b93f763ae5607e8):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x39f40b33de4d22b2c140fccbcf2092ccc24ebdb7ed985716b93f763ae5607e8):
Error at pc=0:197:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:3952)
Unknown location (pc=0:3906)
Unknown location (pc=0:613)

Error in the called contract (0x7080e87497f82ac814c6eaf91d66ac93672927a8c019014f05eb6d688ebd0fc):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x7080e87497f82ac814c6eaf91d66ac93672927a8c019014f05eb6d688ebd0fc):
Error message: SafeUint256: subtraction overflow
Error at pc=0:937:
An ASSERT_EQ instruction failed: 0 != 1.
Cairo traceback (most recent call last):
Unknown location (pc=0:2658)
Unknown location (pc=0:2624)
Unknown location (pc=0:1641)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Unknown location (pc=0:2016)
Error message: ERC1155: burn amount exceeds balance
Unknown location (pc=0:1997)

**Comment by r0man1337** [comment]
should be ok now, it was indexer issue
