### ISSUE TITLE
Feat: space utilization graphic

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#403]
Feature request: Add space utilization graphic (like a progress bar) to the Military Buildings realm page. Bar displays current utilization, and fills up in a different color when you click Construct to show projected utilization.

This graphic could appear on screens where player actions would alter utilization.

![bar](https://user-images.githubusercontent.com/42439169/215358560-6222822d-97ca-415c-b357-af74f7a090ad.png)

**Comment by ponderingdemocritus** [comment]
added in #404

**Comment by palomato** [comment]
![image](https://user-images.githubusercontent.com/42439169/215386785-04952989-9b87-4b4c-8fd3-2f33bf2c78d5.png)
:fire: :fire: :fire:
