### ISSUE TITLE
Feat: army id and dim travel button

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#405]
Can't always remember which army I want to raid a particular realm. I often select an army that is already in transit, but don't realize until signing the transaction fails. When selecting an army to travel:

1) Request army identifier appear near each army (i.e. Army 1)
2) Request 'Travel' button be dimmed and unclickable for armies already in transit

<img width="540" alt="feature" src="https://user-images.githubusercontent.com/42439169/215373685-e96e954f-2c20-424c-a324-9d354e3aac67.png">

**Comment by ponderingdemocritus** [comment]
@palomato pls close if happy :)

**Comment by palomato** [comment]
<img width="519" alt="travel" src="https://user-images.githubusercontent.com/42439169/215810044-982a8e98-77df-4130-8cfc-bb052fd5bb43.png">
:crown: :100:
