### ISSUE TITLE
feat: Atlas Upgrade

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#408]
Now we have a functioning game with a working UX it is time to think about upgrading the Atlas part of the App.

My feeling is that we should use React Three Fibre to do this.

**The features we need:**
- Geojson mapping on land and assets
- Clickable objects within the world
- Animations
- Custom shaders
- Async updates to the objects

We can achieve all of this using Three.js and will be easy to maintain + easy to upgrade from here. We would just replace the map module with this newly created map.

Discuss

**Comment by ponderingdemocritus** [comment]
My thinking is:

- React Three Fibre
- Use - https://github.com/vasturiano/three-geojson-geometry as the paths 
- Custom Shader to give some jazz

**Comment by palomato** [comment]
Would be great if Atlas could help players make in-game decisions.

1) Color code realms by quantity of (resource) in their vaults
2) Color code realms by time remaining until raidable
3) Color code realms by strongest-weakest defensive army

Already working on economic reporting in https://github.com/BibliothecaDAO/economic-reporting
Perhaps Atlas could integrate/display some of this reporting in-game

Far future: connect Vizir AI/enable complex filters
'Show me realms with gold in their vaults, with v.weak defensive army, but not the Order of the Fox'

**Comment by ponderingdemocritus** [comment]
great idea!

I think we can get this done with shaders and make it look slick

**Comment by Amaro-Koberle** [comment]
Yes yes yes, great initiative. 100% in favour.

**Comment by ponderingdemocritus** [comment]
Update on development

Have scoped out what I think is the path we need to take to make this a reality and started a few things. The goal is to reach feature parity with the current Atlas before we go further. This new structure should give signifcantly more performance but also be higher fidelity. 

**To reach feature parity**
- Realms locations
- Visiable continents
- Clickable realms that fly to when clicked
- Searchable resources and display on map
- Visible names of locations on the map


These the individual elements we need to build in R3F:

**First we need to make the geometries**
1. Land - the continents
2. Realms - the Realms mesh. These will be dots to begin with.
3. The World

**Then we make the materials**
1. Continents - land mass with some contrast and coastlines
2. Realms (unsure about how we do these)
3. World - a stylised ocean
4. Atmosphere 
5. Resource selection texture (overlay according to the Resources selected)
6. Background

The project stucture should be very thought out into tight layers which can be toggled.

**Comment by palomato** [comment]
Would it make sense to also have a ‘grid’ layer? Grid layer divides the globe into small polygons or points, not visible to the user

Grid could be used for pathing armies around continents (one day), used by modules in the future, etc.

**Comment by ponderingdemocritus** [comment]
The actual Atlas is just a 3d representation of the on-chain coordinates. So the 'space' already exists, we just need to show it.
