### ISSUE TITLE
New 'Available Resources' Filter / Toggle

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#410]
Request for a filter / toggle for the 'Available Resources' popup screen so that you can see what your resources would be worth in $lords if you sold them.

<img width="650" alt="Screen Shot 2023-01-31 at 10 58 10 PM" src="https://user-images.githubusercontent.com/102257289/215973461-a9822aca-9e60-461e-9783-c1bd307b0a1e.png">

**Comment by ponderingdemocritus** [comment]
#440
