### ISSUE TITLE
bug: Full Screen Mode Black Screen When Signing TX

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#412]
Mac
Brave Browser
Braavos Wallet

When you launch in full screen or maximize later and try to sign any tx the screen goes black and the wallet popup shows up on left side of the screen. Not the end of the world by any means. But someone else brought it up as well.

<img width="1512" alt="Screen Shot 2023-01-31 at 11 05 50 PM" src="https://user-images.githubusercontent.com/102257289/215975873-f3893819-a59c-4456-8ac0-6410793c843e.png">

instead of:

<img width="1446" alt="Screen Shot 2023-01-31 at 11 06 33 PM" src="https://user-images.githubusercontent.com/102257289/215975975-d91b0245-67ca-4ca6-90a3-dadfabc6780b.png">

(I thought I already posted this, apologies if this is the 2nd time.)

**Comment by ponderingdemocritus** [comment]
I'm not sure if this is solvable. This is default browser behaviour.

**Comment by gogibear** [comment]
@ponderingdemocritus should I close this issue?

**Comment by ponderingdemocritus** [comment]
yes closing - with Account Abstraction and Cartridge this will not be relevant
