### ISSUE TITLE
feat: more intuitive introduction to the game - nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#415]
UI/UX - Mouse-overs and blinking “go here” prompts would be very helpful for new players.

IDEA - Auto closing windows that don’t need to be open and opening windows that need attention would be a nice starting guide

IDEA - Voice narration welcoming players and guiding them along

**Comment by ponderingdemocritus** [comment]
All great ideas - plan is to do this once the game design/mechanics are stable otherwise we will be rewriting the wheel many times over

**Comment by ponderingdemocritus** [comment]
closing this as this is known feature planned.
