### ISSUE TITLE
feat: when the game invites you to do something add an obvious button/action nearby/within the invitation - nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#416]
UI/UX - “Would you like to inspect your lands?” Asking a question makes me want to answer, and I don't have an obvious way to do this

<img width="510" alt="Screen Shot 2023-02-01 at 1 18 06 AM" src="https://user-images.githubusercontent.com/102257289/216001760-31766430-b9ce-4662-b064-cf2ddc8a6648.png">

UI/UX - Ok, how? A click-through/on to something to start the castle building?

<img width="622" alt="Screen Shot 2023-02-01 at 1 18 53 AM" src="https://user-images.githubusercontent.com/102257289/216001857-5e5751e1-9b05-4c92-a59b-895f9f80f5b8.png">

**Comment by ponderingdemocritus** [comment]
perhaps we just remove this
