### ISSUE TITLE
bug: happiness emojis, are they accurate? - nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#417]
UI/UX - Is 95 sad? Why? The number feels high.

<img width="626" alt="Screen Shot 2023-02-01 at 1 19 38 AM" src="https://user-images.githubusercontent.com/102257289/216002074-fb091137-ae31-4c7c-b703-1426dc26d250.png">

**Comment by ponderingdemocritus** [comment]
this is being changed
