### ISSUE TITLE
bug: 0's look weird in this instance (redo all of the numbers) - nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#418]
UI/UX - This feels like tiny eyes looking at me or a badly done infinity symbol.

<img width="460" alt="Screen Shot 2023-02-01 at 1 20 54 AM" src="https://user-images.githubusercontent.com/102257289/216002468-9858aca0-2bf8-43e5-87a0-7fcd7ed012b7.png">

**Comment by ponderingdemocritus** [comment]
Should be changed to a '-'
