### ISSUE TITLE
feat: atlas realm icon changes depending on how prosperous - nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#420]
NOTE/IDEA: Map icon changes to reflect how many buildings or the size of realm development.

<img width="159" alt="Screen Shot 2023-02-01 at 1 23 37 AM" src="https://user-images.githubusercontent.com/102257289/216002990-731f1e8d-f0dc-47ab-92a4-5f3ce4f2c311.png">

**Comment by Amaro-Koberle** [comment]
Great idea! I would like to start pivoting my attention back to the map these days. We need to display more information on it. Most of the game should be playable without ever going to the empire page, I think. Right now map info is too scarce to make that a fun experience, too much clicking around required to see how each realm is doing. But I think for now this belongs in the backlog.

**Comment by ponderingdemocritus** [comment]
save this for the Atlas upgrade

**Comment by Fomentador** [comment]
This is information that'll get obfuscated once the eventual fog-of-war algorithm gets developed, so maybe wasted work? Other players shouldn't know the precise state of your military and buildings unless they scout it first - a mechanic that'll only be implemented once fog-of-war is in.
