### ISSUE TITLE
Scroll bar update

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#422]
https://www.figma.com/file/BNxiYPgG7l5ZxO7JXYGdJ0/Print-Design-System?node-id=0%3A1&t=z63QBWAGHxs3UVMY-0

I would like to keep this pattern up across the UI: If it's clickable, it is golden. If it isn't clickable then it is not golden.

![image](https://user-images.githubusercontent.com/53105057/216095503-bfdc63a4-a569-4650-8f7d-f8ed8c1d892d.png)

The scrollbars are clickable and should therefore be be golden. They should also be given some margin with the container that they scroll. I'd like to add arrow buttons on either side.

![image](https://user-images.githubusercontent.com/53105057/216095697-7b94d73f-48ea-4ce0-84a1-91f1df8609c8.png)

The SVGs for the arrow buttons are here:
https://drive.google.com/drive/folders/1isKmsAtsD6NOga1SOtrIXnInIWVcCQ19

**Comment by r0man1337** [comment]
Did a quick search for the solution. It seems that the standard scrollbar styling methods are very limited, as well as there may be problems with adding arrows (it is in the documentation, but in fact the browsers have display problems (at least on macOS)). Need to learn more about ways how this can be done.

**Comment by ponderingdemocritus** [comment]
there is this - https://www.thisdot.co/blog/creating-custom-scrollbars-with-react

But it's pretty custom and I have a feeling will be a nightmare to maintain across multiple browser types

**Comment by Amaro-Koberle** [comment]
If the arrows are a pain, forget about them. Just make the bar golden and give it a few pixels margin to the edge of the container, voila.
