### ISSUE TITLE
bug: Realm search - when you press next you are at the bottom of the list

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#426]
When you are searching through Realms and press Next you end up at the bottom of the list rather than the top. It is an annoyance in that you scroll up to look through realms and then have to scroll back down to press Next for the subsequent page.

![scrollandresourcesvault](https://user-images.githubusercontent.com/102257289/216443500-1956e09c-37a2-4117-83ac-e712cd648368.png)

**Comment by r0man1337** [comment]
Not sure, but may be will be better to replace pagination with infinite scrolling feature? @ponderingdemocritus @gogibear

**Comment by gogibear** [comment]
That works too @r0man1337

**Comment by r0man1337** [comment]
Looks like it was fixed in one of the updates, I now have the scroll goes up
