### ISSUE TITLE
feat: Would it be possible to see the vault value in $lords in the realm search screen

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#427]
As title said Would it be possible to see the vault value in $lords in the realm search screen to help you gauge whether you should attack.

![scrollandresourcesvault](https://user-images.githubusercontent.com/102257289/216443799-8932b932-d1ad-468f-8291-46f2c30098c7.png)

**Comment by r0man1337** [comment]
added in #439
