### ISSUE TITLE
feat: With the auto reconcile feature you don't know how many $lords you are about to spend

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#428]
The auto reconcile feature is handy - too handy atm. You can go crazy building things and have no warning of the amount of $lords you're about to spend until they're gone from your wallet. Could the auto reconcile feature add the lords cost in the tx cart.

<img width="601" alt="Screen Shot 2023-02-02 at 12 39 54 PM" src="https://user-images.githubusercontent.com/102257289/216444864-a29ed1f0-7f30-42a4-80b8-948e92a03325.png">

**Comment by r0man1337** [comment]
added in #439. Also added approximate $lords cost to reconcile button
