### ISSUE TITLE
bug: clicking the mute button only mutes the music.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#430]
![image](https://user-images.githubusercontent.com/53105057/216559514-d35b145d-7dcc-4901-8f9b-2acbbc59c573.png)

Sound FX (like the paper sounds from opening and closing the empire page) are still played even if the button has been clicked.
As it is now, if the icon shows the sound as muted ALL sound should be muted.

Eventually, it might be nice to have alittle pop-up that allows one to turn on and off sound FX and music separately, but for now the single button that we have should act as a master volume and mute all sound when clicked.

**Comment by ponderingdemocritus** [comment]
I think we should introduce a 'Settings' page where users can select these things.

@r0man1337 @RedBeardEth

**Comment by RedBeardEth** [comment]
Yes this is a good idea - I scoped a settings page a while ago and have a fairly good idea of other things to add - I will take this

**Comment by Amaro-Koberle** [comment]
I like it. We could bind it to the wallet name button, and include the wallet modal in there. Just an idea
