### ISSUE TITLE
Cut content underneath tab group.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#431]
![image](https://user-images.githubusercontent.com/53105057/216781720-533b6f43-df7e-484b-85ae-a954a9c0bcd8.png)

The blur effect can be nice in places, I think it's used nicely through-out iOS, for instance. In this case, however, I think it is out of place both in terms of style and readability. The tab group is one of the more important navigation elements, thus it needs to stay readable. If it is on top of bright images, it becomes impossible to read,

**Comment by r0man1337** [comment]
Replaced with dark grey bg
