### ISSUE TITLE
bug: can't see entire available resources screen in windowed mode

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#442]
Firstly thanks for adding the $lords amounts to the Available Resources screen. And perhaps the solution is just to play in full screen mode.

 I use a 14 inch macbook and usually play windowed mode. This is what it looks like:

<img width="1083" alt="Screenshot 2023-02-07 at 5 09 49 PM" src="https://user-images.githubusercontent.com/102257289/217403432-29741023-0c25-404e-81f3-82ce6a888485.png">

If I am playing windowed mode and press maximize on my browser I can see the bottom two resources:

<img width="832" alt="Screenshot 2023-02-07 at 5 17 05 PM" src="https://user-images.githubusercontent.com/102257289/217403909-e4a8bfe3-a448-4230-91bf-b52c65f92cf5.png">

If I use full screen mode from the beginning it works as intended:

<img width="1089" alt="Screenshot 2023-02-07 at 5 17 19 PM" src="https://user-images.githubusercontent.com/102257289/217403971-e95d41e5-ead5-47d5-a7b8-98433643a235.png">

If you think this is worth fixing maybe if you click on the resources the screen pops up and stays available like other screens you can scroll through or adjust the screen size for windowed mode or put the $lords total to the right of the resource instead of below it to decrease screen height.

**Comment by ponderingdemocritus** [comment]
got it - we should make this 3 cols wide
