### ISSUE TITLE
bug: search by relic filter works but you can't see the screen properly

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#443]
Thanks for adding search by relic.

I am using Brave Browser and this happens in windowed mode and full screen mode. The filter works. You can still click the button and search by relic status however the button cuts off so you have to infer what it does.

<img width="336" alt="Screenshot 2023-02-07 at 5 10 05 PM" src="https://user-images.githubusercontent.com/102257289/217404411-1f3b39cb-3a2e-4d0f-969c-3159ed777a3a.png">

<img width="322" alt="Screenshot 2023-02-07 at 5 10 10 PM" src="https://user-images.githubusercontent.com/102257289/217404420-81ec40a0-db27-4524-b0eb-c6850da949c9.png">

**Comment by gogibear** [comment]
Seems like it is aligning based on the right side of the button/popup rather than the left side.

**Comment by ponderingdemocritus** [comment]
@RedBeardEth
