### ISSUE TITLE
We're ALMOST mobile ready, let's just clean things up a bit!

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#444]
I think it's smart to design mobile-first for a host of reasons, but most of all, the heavy space constraints force you to make very careful use of space that translates into great desktop UI that keeps the strong visual hierarchy necessary to make mobile work. Apart from that, our work will be much easier to share when people ask you "what do you work on?", you can whip out your phone, pull up the atlas and have them play. Nice!

So, we're almost there:
![image](https://user-images.githubusercontent.com/53105057/217494106-cbc29e05-3fbb-414d-b2ed-f97c06c3d780.png)

1. The card has to be much closer to the edge, the map surrounding the centre rectangle looks nice, but it leaves too little in the centre. This is the most important change.
2. The labels for the non-selected tabs in the tab group shouldn't be displayed when the tab isn't selected. We don't have the space for it.
3. I have mentioned this elsewhere in an issue: "Your Settled Realms" and "Vizir Reports" are WAY too big. This isn't a word document where you make the section titles bigger than the content. The section titles are at best complementary to the content, and should therefore be very small (and flavour text **short _and_ small**). When we visit the empire page, we don't go there to see the section titles and flavour text, we want to see the news and our realms.
4. I think for now, we can kick the main nav out on mobile. Most of it is redundant anyway, look:
a. Return to atlas: We can return to atlas by pressing the actual map which you can see all around the border. We basically already have the biggest of buttons right there, we should use it.
b. Realms: We can search realms in the search bar. Instead of having a redundant button that takes up space, we should make the search bar as interactive as possible.
c. Bank: We can get to the bank by taping our balance, which is already one of the most prominent screen elements in the whole UI.
d&e. Lore & Leaderboard: I'm not sure these deserve as prominent a place in the UI as they have now, but even then, we can find better places for these. The lower right corner of the UI is still mostly empty, for instance.

Here is an old wireframe I made. It doesn't include the card in the same way, but even within a card, much the same considerations apply.

![image](https://user-images.githubusercontent.com/53105057/217495738-aedc6128-b98c-41f5-820e-05a3ee26eda8.png)

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/217500735-f6a8c237-c4f4-4a01-9a5f-2ce205421764.png)
Made a mock-up of how big the card should be.

**Comment by r0man1337** [comment]
done in #467
