### ISSUE TITLE
Contracts: "Invalid Character"

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#445]
![image](https://user-images.githubusercontent.com/53105057/217614877-83ee9622-fdfe-4a78-9965-569a0619737c.png)

0x042bf805eb946855cc55b1321a86cd4ece9904b2d15f50c47439af3166c7c5e2

![image](https://user-images.githubusercontent.com/53105057/217615062-364996a3-a733-43fb-9e00-75cf61eb146f.png)

No idea what it means or what causes it.

**Comment by ponderingdemocritus** [comment]
can you reproduce this?

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/217771333-be6df477-1b3e-4cb9-a722-96dae0427be1.png)
![image](https://user-images.githubusercontent.com/53105057/217771381-66a68869-f3c9-4315-b093-452cc60df890.png)
![image](https://user-images.githubusercontent.com/53105057/217771439-3cb65442-61b9-40e3-9557-e265e59ba279.png)
I keep getting the error with these transactions scheduled
![image](https://user-images.githubusercontent.com/53105057/217771533-62f5dec0-28f6-42b6-90b7-c55f841d0b42.png)

I should have enough resources. I assume it's one of the transactions.

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/217771939-703e1b81-a45f-4a43-9a03-0109f81177a4.png)
With just the military buildings, I don't get the error.

**Comment by Amaro-Koberle** [comment]
Oh wait, never mind. I do get the same error after clicking approve. It changed to give me that error again.

Maybe something with one of the military buildings?

**Comment by Amaro-Koberle** [comment]
@ponderingdemocritus Okay, I think I found it. I think it must be something to do with resupplying the storehouse:
![image](https://user-images.githubusercontent.com/53105057/217773816-f91769e2-2b61-4a6a-b837-b2f052e96dec.png)

The transaction gives me the same error, even just asking to resupply fish and wheat on one realm. I used the "half" button to choose the amount (in case that is relevant).

**Comment by Amaro-Koberle** [comment]
could it be that the issue is that I was trying to add half a wheat? 
![image](https://user-images.githubusercontent.com/53105057/217777854-7d05c932-b259-4b98-b7a9-49c7cf3c9f1c.png)

Rounding down the number fixed the issue actually.

**Comment by ponderingdemocritus** [comment]
yes this looks like it parsing a wrong character for the food - @r0man1337
