### ISSUE TITLE
Army strength summary is misleading...

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#446]
![image](https://user-images.githubusercontent.com/53105057/217773055-761fa70d-eb8a-474d-960e-5c921ddc4834.png)

I have an army that is 100% elite units, filled to a full 30 battalions. However, the strength summary still reads "weak" on attack. If that army is so moderate, how could I possibly get a strong one?

**Comment by ponderingdemocritus** [comment]
the Army is strong overall.

I will add more refined tiers to the descriptions which will give better context

**Comment by Amaro-Koberle** [comment]
Wait, I think I'm getting it now... in order to be strong in any particular area, I would have to have a less balanced army. So 80% cavalry of 30 troops, for instance, might read as a strong Attack in the cavalry division.

I'm doing some wireframing on army builder and stuff to see if I can make things a bit clearer with visual hierarchy etc.
