### ISSUE TITLE
There is no way to end the battle animation loop

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#447]
![image](https://user-images.githubusercontent.com/53105057/217929499-32bfcb3b-de3f-4e72-a6fa-1c24ff2042f8.png)
We need an exit button and if the sound of the UI is turned off in the lower left, there can be no sound on this.

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/217930872-e477208a-09ba-4e08-8bc7-953307e0a654.png)
I suggest something like this.

**Comment by Amaro-Koberle** [comment]
Note: I realized that one can click the frame buttons to get out of the animation. That's good, but I think we need to indicate an obvious exit as well... Since there is text already, I suggest we move the text out of the centre and down to the bottom where you might find subtitles in a movie or a cut scene. Just place an exit button there that gets one back to the Atlas. Maybe use the globe icon instead of the X, just an idea.

**Comment by r0man1337** [comment]
> Note: I realized that one can click the frame buttons to get out of the animation. That's good, but I think we need to indicate an obvious exit as well... Since there is text already, I suggest we move the text out of the centre and down to the bottom where you might find subtitles in a movie or a cut scene. Just place an exit button there that gets one back to the Atlas. Maybe use the globe icon instead of the X, just an idea.

So after click on exit user will be returned to the Atlas. And when combat is completed we need to show battle results window again?

**Comment by svetaet24** [comment]
What if you make a button to exit the battle and at the end make a popup that tells you that the battle is over and you can see the results?

**Comment by Amaro-Koberle** [comment]
>" What if you make a button to exit the battle and at the end make a popup that tells you that the battle is over and you can see the results?"

This sounds good! @r0man1337 Can we do this?
Put the battle results in some modal...

The thing is that these battles can take a few minutes to resolve (once, I waited closer to 30 minutes...), so we have to make it easy for players to do other stuff in the meantime.

**Comment by r0man1337** [comment]
done in #466 but I think this will need more polishing (need to refactor battle popup system)
