### ISSUE TITLE
Can't buy loads of food.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#448]
![image](https://user-images.githubusercontent.com/53105057/218067510-f0ddb623-7228-41b3-b500-432da76c1541.png)
My people are starving, I want to fill my storehouse quickly without waiting for a harvest. But because the wheat numbers are so ridiculously large (seriously, we need to lop off a bunch of zeros), I can't even enter enough digits into the AMM to buy much wheat. Am I understanding the issue correctly? The bank UI let's me buy ten million of anything at once max. Seems like that ain't much wheat, right? A few lords?

**Comment by ponderingdemocritus** [comment]
we can't lob off 0s unless we do a fundamental rewrite - which we are not going to do. We can adjust everything client side if needed.

We can just increased the max purchasable to 100m which is going to be enough

**Comment by Amaro-Koberle** [comment]
Right. Adjusting client side sounds perfectly fine to me. I don't actually think it matters what happens under the hood (to the player experience, I mean). Under the hood there can be a gazillion digits for all I care, what I am saying is that in the client, the smallest unit that a player would ever consider making any use of should appear as 1, not 10000.
Having a player type in 100000000 is totally silly. It's also quite hard to visually distinguish between orders of magnitude as soon as there are more than four digits involved. 100 million? 10 billion? Let me go count some zeros. Tedious.
