### ISSUE TITLE
bug: Transaction failed on using quick actions

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#459]
![image](https://user-images.githubusercontent.com/53105057/219947559-268fec7d-f535-4996-b69f-8c9da472f885.png)

Transaction failure predicted.
I ran into this using the new UI for harvesting categories of resources from multiple realms at once under the empire page tab "quick actions". I harvested and built some tools. Not sure which caused the error.

```
Error in the called contract (0x3c934d404e76daae48d9b17eb2a4a973938dbd3115bd353e756bcefe0d799a3):
Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:177)
Unknown location (pc=0:163)

Error in the called contract (0x3c934d404e76daae48d9b17eb2a4a973938dbd3115bd353e756bcefe0d799a3):
Error at pc=0:30:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:2635)
Error message: LABOUR: Nothing Generated
Unknown location (pc=0:2491)

Traceback (most recent call last):
  File "<hint4>", line 3, in <module>
AssertionError: assert_not_zero failed: 0 = 0.
```

EDIT:
Maybe this:
![image](https://user-images.githubusercontent.com/53105057/219947518-0dc3dea6-9720-4b00-8947-6c162b9fb218.png)

**Comment by r0man1337** [comment]
fixed in #466
