### ISSUE TITLE
bug: Building meter not accurate / ability to remove buildings

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#461]
If you build too many buildings and you want to change it up there's no ability to remove a constructed building. Can we add that.

 Also one player had the issue that the building meter wasn't accurate. 

<img width="917" alt="screenshot" src="https://user-images.githubusercontent.com/102257289/220306853-759de56e-4a9c-477f-993f-7d66fdd0619a.png">

**Comment by ponderingdemocritus** [comment]
This is dependant on contract upgrade - That will be done first
