### ISSUE TITLE
Add in 2nd param for filters slider

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#90]
Adding another 'bump' in the filter from the top side to narrow the filtering between the two numbers. This will allow more refinement.

**Comment by ponderingdemocritus** [comment]
@micksabox assigning to your ser

**Comment by ponderingdemocritus** [comment]
yes! this is exactly what I was thinking

min - max should always be selected to begin with then the user adjusts

**Comment by ponderingdemocritus** [comment]
These should exist on all sliders so you can narrow the range

**Comment by micksabox** [comment]
Moving to Review / QA
